server:
    address: 0.0.0.0
    port: 8077
management:
    endpoints:
        web:
            exposure:
                include: "*"
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://10.22.7.38:5432/master
        username: postgres
        password: postgres
    jpa:
        show-sql: true
partners:
    - name: khdn
      accessKey: khdn
      ips:
        - 127.0.0.1
        - 10.22.7.99
        - 172.16.68.66
        - 172.16.68.6
        - 0:0:0:0:0:0:0:1
        - "*"

springdoc:
  api-docs:
    path: /swagger-ui.html
