server:
    address: 0.0.0.0
    port: 8077
management:
    endpoints:
        web:
            exposure:
                include: "*"
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://10.22.7.38:5432/master
        username: postgres
        password: postgres
    jpa:
        show-sql: true
    minio:
      url: http://10.22.7.121:9000/
      access-key: vnpay
      secret-key: Vnpay@123
      connect-timeout: 60
      read-timeout: 10
      write-timeout: 60
      bucket: new-mms
      time-share-file: 600
partners:
    - name: khdn
      accessKey: khdn
      ips:
        - 127.0.0.1
        - 10.22.7.99
        - 172.16.68.66
        - 172.16.68.6
        - 0:0:0:0:0:0:0:1
        - "*"

report:
  excel:
    sheet-size: 1000

springdoc:
  api-docs:
    path: /swagger-ui.html
